### ISSUE TITLE
Uploads not working for non-admin users

### ISSUE THREAD

**Issue by A5hleyRich** [A5hleyRich/delightful-downloads#81]
> When logged in to the WP dashboard they can see the "Downloads" menu to the left with "All Downloads" and "Add New" pages shown. However, when trying to upload a file, the uploader reaches 100% then just freezes. They can view and edit the existing uploads under "All Downloads" fine, just not upload new ones.

https://wordpress.org/support/topic/admineditorauthor-uploads?replies=4

**Comment by jevgen** [comment]
Tested this, everything all right, there is no issue in FF.

**Comment by A5hleyRich** [comment]
Also unable to replicate.

**Comment by A5hleyRich** [comment]
Looks like this is an issue with Windows. Need to setup a VM to investigate this and #80.

**Comment by jevgen** [comment]
Not really. I have active Windows user with Editor. No issues like that in latest FF on Win 7.1

**Comment by jevgen** [comment]
I was able to reproduce the issue. If site admin is fiddling with limited interface for certain wp role and calls admin_init instead of admin_menu in his functions.php, he or she will get error in php visible only if debug is on and this will cause the mentioned problem for that particular role.
Turns out to be browser-independent.

**Comment by A5hleyRich** [comment]
@jevgen Can you clarify how you replicated this issue?

**Comment by A5hleyRich** [comment]
Closing for now. Issue should be resolved when uploads moved to default WordPress media modal.
